example.organization.property: "I AM THE DEFAULT ORGANIZATION SERVICE"

server:
    port: 9001
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/yun_sc?characterEncoding=utf8&useSSL=false
        username: root
        password: bear7878
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 200
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    jpa:
        properties:
            hibernate:
                show_sql: true
                format_sql: true
        database: mysql
        hibernate:
            ddl-auto: update
            format_sql: true
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: true
        format_sql: true